### PR TITLE
Update to Go 1.8, syncthing v0.14.24, fix dns patch for ipv6

### PR DESCRIPTION
**Pull request by AudriusButkevicius**

### CODE REVIEW

**Comment by Nutomic** [comment]
Build fails locally and on Travis, with this error:
```
##### Building go_bootstrap for host, linux/amd64.
runtime/internal/sys
2017/03/09 04:32:32 Invalid GOARM value. Must be 5, 6, or 7.
go tool dist: FAILED: /home/travis/build/syncthing/syncthing-android/ext/golang/go/pkg/tool/linux_amd64/compile -pack -o /tmp/go-tool-dist-004540744/runtime/internal/sys/_go_.a -p runtime/internal/sys /home/travis/build/syncthing/syncthing-android/ext/golang/go/src/runtime/internal/sys/arch.go /home/travis/build/syncthing/syncthing-android/ext/golang/go/src/runtime/internal/sys/arch_amd64.go /home/travis/build/syncthing/syncthing-android/ext/golang/go/src/runtime/internal/sys/intrinsics.go /home/travis/build/syncthing/syncthing-android/ext/golang/go/src/runtime/internal/sys/stubs.go /home/travis/build/syncthing/syncthing-android/ext/golang/go/src/runtime/internal/sys/sys.go /home/travis/build/syncthing/syncthing-android/ext/golang/go/src/runtime/internal/sys/zgoarch_amd64.go /home/travis/build/syncthing/syncthing-android/ext/golang/go/src/runtime/internal/sys/zgoos_linux.go /home/travis/build/syncthing/syncthing-android/ext/golang/go/src/runtime/internal/sys/zversion.go: exit status 1
:buildNative FAILED
```

**Comment by AudriusButkevicius** [comment]
I think it's because we are trying to bootstrap arm8 toolchain using Go 1.4, which has no support for that arch. I am not sure how this ever worked.

**Comment by Nutomic** [comment]
Go 1.7 is in Debian Jessie backports, which means F-Droid can use it. So feel free to change the Golang dependency to 1.7

**Comment by AudriusButkevicius** [comment]
You mean use local installation of Go to bootstrap 1.8?
Can I assume that it's just available on the box?

**Comment by Nutomic** [comment]
Yes, I'll contact them to make sure it's installed.

**Comment by AudriusButkevicius** [comment]
Apparently GOARM=8 is no longer a thing:

https://github.com/golang/go/wiki/GoArm

**Comment by Nutomic** [comment]
You also have to unset GOARM in make-syncthing.bash:20.

**Comment by AudriusButkevicius** [comment]
Web edit via mobile, lets see if that works.

**Comment by Nutomic** [comment]
That works, thanks! (IPv6 announce servers arent working for me, but thats probably because my network doesnt support it natively).

Btw it still builds fine for me with no Go installed, so apparently the dependencies didnt change.

**Pull request merged**
