### PR TITLE
Various build improvements/fixes

### PR DESCRIPTION
**Pull request by imsodin**
I'll push the individual commits once it's been proven to work on TC.

### CODE REVIEW

**Comment by calmh** [comment]
> proven to work on TC

Drive by comment: it may or may not work on TC today, but that server is going away at some point. It has multiple failed disks, some other hardware problem I'm not sure of, and it's only due to its robust constitution that it's not already dead. I don't intend to fix it...

**Comment by imsodin** [comment]
> Drive by comment: it may or may not work on TC today, but that server is going away at some point. It has multiple failed disks, some other hardware problem I'm not sure of, and it's only due to its robust constitution that it's not already dead. I don't intend to fix it...

Oh I realized something was happening, but I thought it only affected some server running windows stuff. I'll look into github actions and hope it will keep jugging along until I do.

**Comment by calmh** [comment]
Yeah the Windows VM (on that host) was the first casualty of actual data loss, while the rest of it keeps chugging along...

**Comment by imsodin** [comment]
Looks like it's already failing - some git objects missing. I guess I'll keep this PR around and extend it for actions eventually, not today.

**Comment by LinuxOnTheDesktop** [comment]
Does the project (synthing-android) need a new (real or virtual) server? If so, you could try to fund it via donations - but perhaps the idea is not practical.

**Comment by imsodin** [comment]
That's not the issue, at least likely not the main issue which is time. It's probably easier/quicker to setup github actions than to (re-)provision TC on some VM.

**Comment by LinuxOnTheDesktop** [comment]
@imsodin 

I'm afraid I don't understand the phrase '(re-)provision TC on some VM'.

At any rate: I do look forward to the next release, because I am on Syncthing 1.23.5 and seemingly that version is causing problems for me - principally problems syncing with with my other, non-Android, devices - and I hope that [the subsequent commits](https://github.com/syncthing/syncthing-android/compare/1.23.5...main) will fix that. (I could try to build syncthing-android myself, but I'm not using to building on Android and my phone isn't rooted.)

**Comment by imsodin** [comment]
Ha, I can see how that's pretty much gibberish: TC is TeamCity, the software currently in-use to build everything, and VM is a virtual machine (server).

Anyway the new build will be made available somehow, that's not an issue. I doubt it will help anything with sync problems though, nothing changed there. Please post on the forum if you'd like help with that.

**Pull request closed without merging**
