### PR TITLE
And another one

### PR DESCRIPTION
**Pull request by AudriusButkevicius**

### CODE REVIEW

**Comment by Nutomic** [comment]
Uh sure, why not :o 

At least it increases the issue/pr ID counter :D

**Comment by AudriusButkevicius** [comment]
I am now close to making a build myself.

**Comment by licaon-kter** [comment]
Get [Babun](https://babun.github.io) or [wait a bit](http://blog.dustinkirkland.com/2016/03/ubuntu-on-windows.html)

**Comment by AudriusButkevicius** [comment]
So I am fine with cygwin, but you can't bootstrap go on Windows using cygwin, nor do I have non VC compiler which seems to be required to bootstrap.

**Comment by licaon-kter** [comment]
Or a known working solution: VirtualBox+Lubuntu+AndroidStudio

**Pull request closed without merging**
