### PR TITLE
Explain requirement for notification in "Run as foreground" setting (fixes #715)

### LINKED ISSUE #715: Notification types should depend on foreground service state
As of 0.8.1

If Experimental/Foreground is disabled (this is how it looks now):
* Normal
* Low Prio
* None

If Experimental/Foreground is enabled (there is no None as a Notification is needed for the foreground service anyway):
* Normal
* Low Prio (activated by default)

### PR DESCRIPTION
**Pull request by capi**
Add suggested explanation of #715 to `run_as_foreground_service_summary`.

### CODE REVIEW

**Comment by Nutomic** [comment]
@licaon-kter Do you think this is enough to fix the issue?

@capi Can you try to keep commit messages under 80 characters, so Github and other tools don't cut the end off? That should make it easier to read logs :)

**Comment by AudriusButkevicius** [comment]
`other tools`  - your VT100?

**Comment by capi** [comment]
@Nutomic Ups, sorry, yeah, normally I commit via git-gui, which warns about this. This one was done via shell and `-m`, so I missed out. Will try to behave better in the future :)

@AudriusButkevicius :D

**Comment by licaon-kter** [comment]
@Nutomic It's not a fix but a clarification, maybe when foreground exits experimental state this needs a re-evaluation.

**Comment by Nutomic** [comment]
@capi Okay, I'll merge this after you shorten the commit message.

@licaon-kter Please remind us then ;)

**Comment by capi** [comment]
@Nutomic commit message shortened

**Comment by Nutomic** [comment]
Thanks :)

**Pull request merged**
