### PR TITLE
Really fix DNS

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
The previous patch was merged against a different version of Go, plus had bugs.
Now given I am able to build stuff, this seems to do the right job.

You should look at the raw patch rather than the diff to the diff.

### CODE REVIEW

**Comment by Nutomic** [comment]
I suppose this won't work if the previous version of the patch was applied?

@Zillode Does Jenkins discard changes in the submodule after each build? Or do we have to do something to get rid of the old patch?

**Comment by AudriusButkevicius** [comment]
atleast I had to do that

**Comment by Nutomic** [comment]
Okay I just wiped the workspace from Jenkins (didn't know you can do that). I hope that's enough.

**Comment by AudriusButkevicius** [comment]
Your "Oh this branch builds fine" builds master anyway, so that doesn't matter much :D

**Comment by Nutomic** [comment]
I'm not sure what you mean. We have to make sure the patch goes into new release builds, right?

**Comment by AudriusButkevicius** [comment]
What I mean is if you look at:

http://android.syncthing.net/job/Syncthing-Android-PR/197/console

In every build you will see:

`Checking out Revision 09bba7140aa3d811edf1c6322e24731a1978b06b (origin/master)`

**Comment by Nutomic** [comment]
Right, I guess it's fine. I just wanted to be sure, and I really don't understand Jenkins.

**Comment by Zillode** [comment]
`Delete workspace before build starts` is now enabled

**Pull request merged**
