### PR TITLE
Compile Syncthing using the goos=android Go1.4 flag for ARM (fixes #46 and fixes #57)

### LINKED ISSUE #46: Go support for android
Seen this? :)

https://docs.google.com/document/d/1N3XyVkAP8nmWjASz8L_OjjnjVKxgeVBjIsTr5qIUcA4/preview?sle=true

### LINKED ISSUE #57: dynamic dns
Hi,
¿Does it work with dynamic dns like duckdns.org?

I'm using the phone as a modem for a laptop. Both are configured to sync with the same desktop using duckdns.org. The laptop find the desktop but the phone doesn't.

Thanks.

### PR DESCRIPTION
**Pull request by Zillode**
Might also fix https://github.com/syncthing/syncthing/issues/1132

### CODE REVIEW

**Comment by Zillode** [comment]
(don't merge yet, there seems to be a problem https://forum.syncthing.net/t/is-syncthing-android-for-0-11-available-for-testing/2443/36 )

**Comment by Zillode** [comment]
W/SyncthingNativeCode(13527): error: only position independent executables (PIE) are supported.

**Comment by Zillode** [comment]
(needs `-extldflags '-fPIE -pie'` in build.go of upstream)

**Comment by Nutomic** [comment]
Is this still relevant with Go 1.5?

**Comment by Zillode** [comment]
Yes, 1.5 doesn't fix it as far as I've tested (but this should be verified).

**Comment by calmh** [comment]
Does this work? Does it give us DNS on android?

**Comment by AudriusButkevicius** [comment]
-tag netgo gives us dns on android.

**Comment by calmh** [comment]
Can someone with an Android verify this, so we can get the build process straightened out, and then forget about ugly DNS-to-IP hacks for Android? :)

**Comment by Nutomic** [comment]
I just tried again to get Go 1.5 working. I have 1.5 installed, but make.bash complained about missing `$GOROOT_BOOTSTRAP`. I tried setting `GOROOT_BOOTSTRAP=$GOROOT`, but that only gives more errors. Where do I have to point this?

**Comment by AudriusButkevicius** [comment]
You have to point it at go 1.4

**Comment by Nutomic** [comment]
Ok I got the build working, but discovery still fails:
```
I/SyncthingNativeCode( 9268): [2SKQS] 2015/10/01 13:56:26.822286 client_udp.go:106: DEBUG: discover udp6://announce-v6.syncthing.net:22026: broadcast resolve: lookup announce-v6.syncthing.net on [::1]:53: read udp [::1]:45777->[::1]:53: read: connection refused; trying again in 1m0s
I/SyncthingNativeCode( 9268): [2SKQS] 2015/10/01 13:56:26.850305 client_udp.go:106: DEBUG: discover udp4://announce.syncthing.net:22026: broadcast resolve: lookup announce.syncthing.net on [::1]:53: read udp [::1]:40185->[::1]:53: read: connection refused; trying again in 1m0s
```

I put the `-tag netgo` after `make.bash`, is that correct?

**Comment by AudriusButkevicius** [comment]
No, as you go build syncthing I think.

**Comment by Nutomic** [comment]
That just gives me "unknown command". I've also uploaded my progress on the go1.5 branch.

**Pull request closed without merging**
