### PR TITLE
Fix Lint warning "extraneous text in resource file"

### PR DESCRIPTION
**Pull request by ghost**
affected resource :   folder fragment
I verified this build correctly after removing the extra tag close which is wrong.
Please correct me if this would have needed review.
I'm merging this according to Nutomic's last comment about minor changes.

### CODE REVIEW

**Comment by Catfriend1** [comment]
BUILD LOG
`> Configure project :app
Signing not ready. Did you specify a signingConfig for the variation Release?

> Task :app:lint
Ran lint on variant release: 109 issues found
Ran lint on variant debug: 109 issues found
Wrote HTML report to file:///home/builduser/syncthing-android/app/build/reports/lint-results.html
Wrote XML report to file:///home/builduser/syncthing-android/app/build/reports/lint-results.xml


BUILD SUCCESSFUL in 15s
47 actionable tasks: 7 executed, 40 up-to-date
`

**Comment by Catfriend1** [comment]
@AudriusButkevicius Sorry that we now have two commits showing up for this one on the master history. Can you please give me a hint on how you do the merge as one commit?

**Comment by AudriusButkevicius** [comment]
Squash merge. But you should also fix up your PR titles to start with a capital and potentially reference the relevant issue.

**Comment by Catfriend1** [comment]
Thanks, I'll do this from now on. Also corrected the capital letter for this and the new PR. For this one, no issue was created as it was no end user issue but a syntax error.

**Pull request merged**
