### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lkwg82**
fixed broken screenshots

### CODE REVIEW

**Comment by wweich** [comment]
Why use a Wikipedia image for play store, instead of th official one?
https://play.google.com/intl/en_us/badges/images/apps/en-play-badge.png

**Comment by Nutomic** [comment]
Damn, I never notice when I break the readme images. Thanks for fixing it. And I agree, using the official Google Play image seems better.

**Comment by lkwg82** [comment]
1. I did not know the official path. 
2. Svg is smooth with resizing.
Am 27.03.2016 10:05 vorm. schrieb Wulf Weich <notifications@github.com>:Why use a Wikipedia image for play store, instead of th official one?
https://play.google.com/intl/en_us/badges/images/apps/en-play-badge.png

**Comment by Nutomic** [comment]
Yeah please use the official image. Also, I don't see why you changed the link to HTML, markdown is totally fine.

**Comment by lkwg82** [comment]
html was used to explicitly set the size

**Comment by Nutomic** [comment]
Ah I didn't see that. Can you squash the commits though?

**Comment by lkwg82** [comment]
Of course. 

Btw. can we integrate st-bot to merge PRs easily?

**Comment by Nutomic** [comment]
Thanks. I haven't looked into the not yet, because we don't have that many PRs here. But maybe I'll get around to it.

**Pull request merged**
