### PR TITLE
Go 1.7.3 support

### PR DESCRIPTION
**Pull request by AudriusButkevicius**

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
So spent 3 evenings, 2 of them getting this to build on Windows, just to realize Go 1.7 requires a port number for the DNS servers.

**Comment by Nutomic** [comment]
Great, thanks :)

Can you add a reference to #219 in your commit message, and update the Windows build instructions in the readme?

**Comment by AudriusButkevicius** [comment]
Hopefully that's good enough.

**Comment by Nutomic** [comment]
Great :)

**Pull request merged**
