### PR TITLE
added a proper notification icon

### PR DESCRIPTION
**Pull request by t184256**
I discovered that adding a proper (smaller, all-white) notification icon seems to fix crashing syncthing with themed icon ((bug I filed to syncthing)[https://github.com/syncthing/syncthing-android/issues/330], (bug I filed to TwelF icon theme)[https://gitlab.com/xphnx/twelf_cm12_theme/issues/17]. I see no downsides for this change, so I'm asking to merge it.

### CODE REVIEW

**Comment by Nutomic** [comment]
This might be nitpicking, but I think the lines are a bit too small, maybe you can make them bigger? https://i.imgur.com/pQxgcYu.png

Also, I just noticed that `graphics/ic_launcher_full.png` and `graphics/ic_stat_notify_full.png` should be vector graphics, but I can't blame that on you. (There are svg graphics [upstream](https://github.com/syncthing/syncthing/tree/master/assets)).

**Comment by t184256** [comment]
I actually made the lines wider for the icon that started it all: the one I've made for TwelF. 
https://gitlab.com/t184256/twelf_cm12_theme/uploads/dbd10a58f07510057a2db54c0e5f5b52/syncthing.svg
Should I redo the notification icon? Should I recreate it from the upstream svgs? Can I reuse what I've done for the TwelF icon? Should I just wait till you merge this request? Or should I modify it or open another one? I'm confused what to do next since you've not closed this merge request. I'd like to hear from you what to do next.

**Comment by Nutomic** [comment]
I don't know how you should make the icon, whatever works for you really. I've replaced `raphics/ic_launcher_full.png` with an svg now, so that would be nice for your icon as well.

You can just make a new commit with the changes and push them. Before I merge it, you should [squash your commits](http://stackoverflow.com/a/24527934).

**Comment by t184256** [comment]
I tried hard to comply. Hope I got it right now. Will you merge?

**Comment by Nutomic** [comment]
Looks good :+1: 

Can you just rebase against master so we get a clean history? (Command is `git rebase upstream/master`, where upstream is your alias for this repo).

**Comment by t184256** [comment]
Just for the record, I did:
```
$ git remote add upstream git@github.com:syncthing/syncthing-android.git
$ git fetch upstream
remote: Counting objects: 83, done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 83 (delta 28), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (83/83), done.
From github.com:syncthing/syncthing-android
 * [new branch]      cert-pinning -> upstream/cert-pinning
 * [new branch]      license    -> upstream/license
 * [new branch]      license-mplv2 -> upstream/license-mplv2
 * [new branch]      master     -> upstream/master
 * [new branch]      set-user-pw-on-install -> upstream/set-user-pw-on-install
 * [new tag]         0.5.28     -> 0.5.28
$ git rebase upstream/master
First, rewinding head to replay your work on top of it...
Applying: added a proper notification icon
$ git push --force
Counting objects: 94, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (65/65), done.
Writing objects: 100% (94/94), 19.84 KiB | 0 bytes/s, done.
Total 94 (delta 43), reused 0 (delta 0)
To git@github.com:t184256/syncthing-android.git
 + 7d6798f...d7285f1 master -> master (forced update)

**Comment by Nutomic** [comment]
I probably commited something in between, sorry about that. Unfortunately, I don't know a better way to handle this.

Thanks for your contribution :)

**Pull request merged**
