### PR TITLE
fixes RestApi options for 'listenAddress'

### PR DESCRIPTION
**Pull request by lkwg82**
this fixes display of syncthing listenAddress(es) in options menu.

### CODE REVIEW

**Comment by Nutomic** [comment]
Thanks! Looks like no one even noticed that...

**Comment by lkwg82** [comment]
There is "upnpEnabled" left, but I dont know how the api changed. ;)

**Comment by AudriusButkevicius** [comment]
It didn't at all. It just does more than before.

**Comment by Zillode** [comment]
I think it was renamed to `natEnabled`?

**Pull request merged**
