### PR TITLE
Work around for Samsung's MenuBuilder bug (fixes #307).

### LINKED ISSUE #307: NoClassDefFoundError
From Play logs:
```
java.lang.NoClassDefFoundError: android.support.v7.internal.view.menu.MenuBuilder
at android.support.v7.app.ActionBarActivityDelegateBase.initializePanelMenu(ActionBarActivityDelegateBase.java:914)
at android.support.v7.app.ActionBarActivityDelegateBase.preparePanel(ActionBarActivityDelegateBase.java:964)
at android.support.v7.app.ActionBarActivityDelegateBase.doInvalidatePanelMenu(ActionBarActivityDelegateBase.java:1182)
at android.support.v7.app.ActionBarActivityDelegateBase.access$100(ActionBarActivityDelegateBase.java:79)
at android.support.v7.app.ActionBarActivityDelegateBase$1.run(ActionBarActivityDelegateBase.java:115)
at android.os.Handler.handleCallback(Handler.java:725)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5299)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
at dalvik.system.NativeStart.main(Native Method)
```

### PR DESCRIPTION
**Pull request by Zillode**
(untested, I have no Samsung device)
Still works for non-Samsung phones

### CODE REVIEW

**Comment by Nutomic** [comment]
Do you have a link for this?

I don't see why we'd have to keep classes if we don't even use proguard. Also, does this mean we now have to deal with scrambled class names etc in logs?

**Comment by Zillode** [comment]
Not sure about the scrambled names, maybe we should minifyEnabled to false to avoid this?

**Comment by Nutomic** [comment]
You could just try it by making a release build and put `throw new Exception()` somewhere. Or maybe I'm faster ;)

If minifyEnabled is false, I assume the proguard file isn't even read.

**Comment by Nutomic** [comment]
Just checked, class names aren't scrambled so it's good.

Can you just put a description/link into the proguard file please?

**Comment by Nutomic** [comment]
Ok it's good, just add the comment.

**Comment by Zillode** [comment]
done

**Pull request merged**
