### PR TITLE
Start the correct ZXing barcode scanner (fixes #322).

### LINKED ISSUE #322: java.lang.SecurityException: Permission Denial: com.google.zxing.client.android.SCAN
From Play logs:
```
java.lang.IllegalStateException: Could not execute method of the activity
at android.view.View$1.onClick(View.java:3830)
at android.view.View.performClick(View.java:4445)
at android.view.View$PerformClick.run(View.java:18446)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5146)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at android.view.View$1.onClick(View.java:3825)
... 11 more
Caused by: java.lang.SecurityException: Permission Denial: starting Intent { act=com.google.zxing.client.android.SCAN cat=[android.intent.category.DEFAULT] flg=0x4080000 cmp=br.com.gabba.Caixa/com.google.zxing.client.android.CaptureActivity } from ProcessRecord{427077c0 31938:com.nutomic.syncthingandroid/u0a141} (pid=31938, uid=10141) not exported from uid 10062
at android.os.Parcel.readException(Parcel.java:1472)
at android.os.Parcel.readException(Parcel.java:1426)
at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:2115)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1419)
at android.app.Activity.startActivityForResult(Activity.java:3424)
at android.app.Activity.startActivityForResult(Activity.java:3385)
at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:832)
at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:907)
at com.nutomic.syncthingandroid.fragments.DeviceSettingsFragment.onClick(DeviceSettingsFragment.java:301)
at com.nutomic.syncthingandroid.activities.SettingsActivity.onClick(SettingsActivity.java:95)
... 14 more
```

### PR DESCRIPTION
**Pull request by Zillode**
Based on http://stackoverflow.com/questions/11388450/using-zxing-barcode-scanner-causes-securityexception and https://github.com/zxing/zxing/wiki/Scanning-Via-Intent#intentintegrator

### CODE REVIEW

**Comment by Nutomic** [comment]
It would be nice if we could pull the dependency from [Maven Central[(http://search.maven.org/#browse|-1891052958) instead of copying the source. Can you try if that works?

I suppose we couldn't add unitag then, but I would file that as an issue at zxing.

**Comment by Zillode** [comment]
Updated with maven :+1: 

com.unitag.scanner does not work because it does not register itself as a traditional scanner. We would need to create an API token and register to closed source software.

**Comment by Nutomic** [comment]
Just tried to test this, but it seems there are some other changes mixed in:

```
From git://github.com/Zillode/syncthing-android
 * branch            fix-scanner -> FETCH_HEAD
Updating 24ba984..1fcbe0b
Fast-forward
 build.gradle                                                                               |  5 ++++-
 proguard-android.txt                                                                       |  3 +++
 src/androidTest/java/com/nutomic/syncthingandroid/test/syncthing/SyncthingServiceTest.java |  5 +++--
 src/androidTest/java/com/nutomic/syncthingandroid/test/util/FoldersAdapterTest.java        |  7 ++++---
 src/main/AndroidManifest.xml                                                               | 11 +++++++----
 src/main/java/com/nutomic/syncthingandroid/activities/MainActivity.java                    | 98 ++++++++++++++++++++++++++++++++++++++++++++++++++++--------------------------------------------
 src/main/java/com/nutomic/syncthingandroid/fragments/DeviceSettingsFragment.java           | 28 ++++++++++++++--------------
 src/main/java/com/nutomic/syncthingandroid/fragments/DevicesFragment.java                  |  2 +-
 src/main/java/com/nutomic/syncthingandroid/fragments/DrawerFragment.java                   |  8 ++++----
 src/main/java/com/nutomic/syncthingandroid/fragments/FoldersFragment.java                  |  2 +-
 src/main/java/com/nutomic/syncthingandroid/syncthing/GetTask.java                          |  2 +-
 src/main/java/com/nutomic/syncthingandroid/syncthing/RestApi.java                          |  3 ++-
 src/main/java/com/nutomic/syncthingandroid/syncthing/SyncthingRunnable.java                | 46 +++++++++++++++++++++++++++++++++++++++++++++
 src/main/java/com/nutomic/syncthingandroid/syncthing/SyncthingService.java                 |  8 +++++---
 src/main/res/values-de/strings.xml                                                         | 26 ++++++++++++++++++++++++--
 src/main/res/values-ru/strings.xml                                                         | 89 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-
 16 files changed, 260 insertions(+), 83 deletions(-)
 create mode 100644 proguard-android.txt
```

`git diff master` also looks different than the diff here. Anyway, the code looks good so feel free to merge this if you've tested it and figured out this weirdness.

**Comment by Nutomic** [comment]
Found the problem:

We need to call `new IntentIntegrator(Fragment)`, so the result doesn't go to the activity. Problem is, they only support `android.preference.PreferenceFragment` while we use `android.support.v4.preference.PreferenceFragment`.

https://github.com/zxing/zxing/issues/291

**Comment by Zillode** [comment]
I'm not sure, you're asking them to support an unofficial library, I doubt that'll work.
+1 for copying the source and be done with it=)

**Comment by Nutomic** [comment]
It's all about [this](http://developer.android.com/reference/android/support/v4/app/Fragment.html) class that comes with the suppor v4 library.

And I don't want to maintain any extra code if we can help it.

**Comment by Zillode** [comment]
Ah, that's different from the [PreferenceFragment](https://github.com/kolavar/android-support-v4-preferencefragment) you propose in the issue

**Comment by Nutomic** [comment]
PreferenceFragment implements Fragment ;)

**Comment by Nutomic** [comment]
No reply in a week. I say we drop Gingerbread support.

**Pull request closed without merging**
