### PR TITLE
downgrade build tools, try to fix #690

### LINKED ISSUE #690: Nexus 6p: App crashes on adding new device
Nexus 6P, stock image, up-to-date. On fresh install, hitting the '+' sign in device tab causes it to crash every time. Does not happen on Nexus 10, stock, up to date. (Only two devices I tried it on so far)

### PR DESCRIPTION
**Pull request by lkwg82**
hope there will be apks to fix it

relates to #690

### CODE REVIEW

**Comment by Nutomic** [comment]
So you didn't actually check if DevicesFragment still worked after your update?

**Comment by lkwg82** [comment]
I checked the app on my phone and did not noticed any issue. 
This is just to make sure the upgrade is not the cause.

**Comment by lkwg82** [comment]
I hope we can close this PR without merging it :).


btw:  the build hangs

**Comment by lkwg82** [comment]
Who can check the hanging build?

**Comment by Nutomic** [comment]
Jenkins seems to be broken since a few weeks or so, and I have no idea how to fix it. @lkwg82 Do you know about this stuff?

Regarding this PR, I'm currently busy with my bachelor thesis, so I probably won't have time to review or publish a new release. I'll probably do it after I turn in my thesis, together with the Syncthing v0.14 release.

**Comment by lkwg82** [comment]
It is ok to concentrate on bachelor thesis.

**Pull request closed without merging**
