### PR TITLE
Fix Transifex config to make pull script work again.

### PR DESCRIPTION
**Pull request by acolomb**
Just needed an update to the config file syntax.  Now the `scripts/pull-translations.bash` command works again for me.  Where can I see how this is currently failing?

### CODE REVIEW

**Comment by acolomb** [comment]
I guess this needs a `tx push -s` first, to avoid the error caused by removed strings.  However this fails on my side with:

```
# Getting info about resources

syncthing-android.description_fulltxt - Error while fetching stats, 404, not_found: No `Project` resource found with the identifier `o:syncthing:p:syncthing-android`
syncthing-android.description_shorttxt - Error while fetching stats, 404, not_found: No `Project` resource found with the identifier `o:syncthing:p:syncthing-android`
syncthing-android.stringsxml - Error while fetching stats, 404, not_found: No `Project` resource found with the identifier `o:syncthing:p:syncthing-android`
syncthing-android.titletxt - Error while fetching stats, 404, not_found: No `Project` resource found with the identifier `o:syncthing:p:syncthing-android`
[##############################] (4 / 4)
```

Strangely, pulling works perfectly OK.  Maybe my API key doesn't have push access?  But then why does it get a 404 while "fetching status"?

**Comment by imsodin** [comment]
That's likely the permissions, I have an API key in ~/.transifexrc locally and pushing worked fine from this branch. You can generate your own in your user settings. If that still doesn't work, you might not have the required project permissions - let me know if that's the case and I'll try to figure out how to remedy that.

**Comment by acolomb** [comment]
> That's likely the permissions, I have an API key in ~/.transifexrc locally

Same here.

> you might not have the required project permissions - let me know if that's the case and I'll try to figure out how to remedy that.

That was my assumption as well.  If you don't mind, let's see if you can assign additional permissions for my user to push.

However, the tx CLI interaction clearly displays it's failing at a step where it's just checking for the existence of the project to collect stats.  I've tested all related endpoints on their docs page with my API key and as expected, it works there.  Maybe just the client giving some erroneous failure reason.

**Comment by imsodin** [comment]
I made you a project maintainer on syncthing-android - I'd expect that should give you all the possible permissions to be had.

**Comment by acolomb** [comment]
That worked apparently, just pushed the state of this PR to Transifex.  Pulled in current translation state as well into this PR.

**Comment by acolomb** [comment]
@imsodin Okay to merge this?  Then I'd rebase the weblate branch and get to fixing the expected conflicts there.

**Comment by acolomb** [comment]
OK, that was just the `run_conditions_title` being altered in commit 892fdea2ea359830980d598b4fd2a016829906d4.  We probably should have changed the key as well then, but anyway now that the English string was updated, the translations got discarded by Transifex (rightfully).

**Review by imsodin — APPROVED** [review]

**Pull request merged**
