### PR TITLE
Support for adaptive icons

### PR DESCRIPTION
**Pull request by lokesh-krishna**
This PR adds support for adaptive icons on devices running Android 8.0 or higher while devices running older versions of Android will continue to see the legacy icon.

The PR also additionally moves launcher icons from their present `drawable` folders to `mipmap` folders.

The app needs to be built against the latest SDK in order to support adaptive icons.

The icons can be seen at #1055.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@calmh any ideas about the docker image disappearing?

**Comment by Catfriend1** [comment]
@lokesh-krishna I've inspected the build log. According to https://stackoverflow.com/questions/29243121/cannot-resolve-symbol-drawable-ic-launcher do I unterstand it correctly all drawable folders have to be changed to mipmap?

**Comment by AudriusButkevicius** [comment]
The build failures are genuine:

```
[19:31:14]	/opt/buildagent/work/19a8ed19ae4d1032/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:29: AAPT: error: resource drawable/ic_launcher (aka com.nutomic.syncthingandroid.debug:drawable/ic_launcher) not found.
[19:31:14]	    
[19:31:14]	/opt/buildagent/work/19a8ed19ae4d1032/app/build/intermediates/manifests/full/debug/AndroidManifest.xml:29: error: resource drawable/ic_launcher (aka com.nutomic.syncthingandroid.debug:drawable/ic_launcher) not found.
[19:31:14]	error: failed processing manifest.
```

**Comment by Nutomic** [comment]
@Catfriend1 No, only the launcher icons need to be moved to the `mipmap` folder. All in-app icons should stay in `drawable`.

@lokesh-krishna You need to replace all references in the project to `drawable/ic_launcher` with `mipmap/ic_launcher`.

**Comment by lokesh-krishna** [comment]
@Nutomic, so sorry I missed that. On it!

**Comment by Catfriend1** [comment]
I will later do a test on Android 7.1.2 how this looks on "older" roms and report back. According to comments in https://github.com/syncthing/syncthing-android/issues/1055 this PR looks ok to me.

**Comment by calmh** [comment]
@AudriusButkevicius what docker image disappearing where?

**Comment by AudriusButkevicius** [comment]
The android image disappeared from the build boz but I've rebuilt it.

**Comment by calmh** [comment]
Hmm. I did an Ansible run a couple of days back to upgrade the TC server container etc. Far as I can tell it's not *supposed* to remove other images as part of that, though... We might want to add the Dockerfile/whatever to the ansible repo and have it manage the android builder image, for great self-documentation etc.

**Comment by Catfriend1** [comment]
Ok, lgtm.
Android 7.1.2 looks like this (right icon is debug build)
grafik
Android 8.0 looks like this (right icon is debug build):
grafik

**Comment by Catfriend1** [comment]
@lokesh-krishna Done, I've attached the new gradient design file.
[Gradient_432.zip](https://github.com/syncthing/syncthing-android/files/2030163/Gradient_432.zip)

**Comment by lokesh-krishna** [comment]
Thank you so much! The new icon looks gorgeous!  

screenshot_2018-05-23 adapticon
screenshot_2018-05-23 adapticon 1

**Comment by Catfriend1** [comment]
@AudriusButkevicius May I hit the merge button? Lgtm? Looks good from me, visually and working on Android 7.1.2 and Android 8.x

**Comment by AudriusButkevicius** [comment]
Is it just optical illusion because of the connection points or is the logo a bit shifted to the right?

**Pull request merged**
