### PR TITLE
Update gradle

### PR DESCRIPTION
**Pull request by imsodin**
gradle-play-publisher 2.4.0 has a fix for our new build problems and requires a newer gradle - lets hope this works out of the box (https://github.com/Triple-T/gradle-play-publisher/issues/629).

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
My money is that this will cause new issues when releasing, but lets see.

**Comment by imsodin** [comment]
> My money is that this will cause new issues when releasing, but lets see.

I am not gonna disagree with that, but at least it fixes one issue that makes release currently nearly impossible.

**Comment by imsodin** [comment]
@AudriusButkevicius Are you ok with merging this and the publisher and seeing how it goes?

**Comment by AudriusButkevicius** [comment]
You have my blessing

**Pull request merged**
