### PR TITLE
go: DNS patch for go 1.7 (fixes #723)

### LINKED ISSUE #723: DNS patch not working with Go 1.7
Building GO fails with:

HEAD сейчас на 5dc7525 syscall: mksyscall_windows.go: put path separator in suffix for matching GOROOT
Applying /home/user/syncthing-android/patches/golang/all/dns.patch
patching file net/dnsclient_unix.go
Hunk #1 FAILED at 279.
1 out of 1 hunk FAILED -- saving rejects to file net/dnsclient_unix.go.rej
patching file net/dnsconfig_unix.go
Hunk #1 FAILED at 8.
Hunk #2 FAILED at 33.
Hunk #3 succeeded at 126 with fuzz 2 (offset 16 lines).
2 out of 3 hunks FAILED -- saving rejects to file net/dnsconfig_unix.go.rej

As i understand there are no strings in these .go files which are had to be replaced or I am doing something wrong?

Version Information

App Version: 0.8.1
Syncthing Version: 0.14.4
Android Version:

### PR DESCRIPTION
**Pull request by AudriusButkevicius**
Someone needs to check if this builds

### CODE REVIEW

**Comment by Nutomic** [comment]
Something is wrong, I get this error:
```
Installed Go for linux/amd64 in /home/felix/workspace/syncthing-android/ext/golang/go1.4
Installed commands in /home/felix/workspace/syncthing-android/ext/golang/go1.4/bin
~/workspace/syncthing-android
~/workspace/syncthing-android/ext/golang/go/src ~/workspace/syncthing-android
HEAD is now at 57e459e [release-branch.go1.6] go1.6.2
Applying /home/felix/workspace/syncthing-android/patches/golang/all/dns.patch
patching file net/dnsconfig_unix.go
Hunk #1 FAILED at 9.
Hunk #2 FAILED at 40.
Hunk #3 FAILED at 49.
Hunk #4 FAILED at 126.
4 out of 4 hunks FAILED -- saving rejects to file net/dnsconfig_unix.go.rej
````

What's with the changelog, it's all whitespace? And you should also update the Golang submodule in the PR ;)

**Comment by AudriusButkevicius** [comment]
I'm modifying stuff via github, as I nuked my android build env.

**Comment by Nutomic** [comment]
```
Installed Go for linux/amd64 in /home/felix/workspace/syncthing-android/ext/golang/go1.4
Installed commands in /home/felix/workspace/syncthing-android/ext/golang/go1.4/bin
~/workspace/syncthing-android
~/workspace/syncthing-android/ext/golang/go/src ~/workspace/syncthing-android
HEAD is now at 0d81858 go1.7
Applying /home/felix/workspace/syncthing-android/patches/golang/all/dns.patch
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- net/dnsconfig_unix.go      2016-08-15 18:48:00.000000000 -0400
|+++ net/dnsconfig_unix.go      2016-08-19 19:16:16.343343090 -0400
--------------------------
File to patch:
Skip this patch? [y]
Skipping patch.
4 out of 4 hunks ignored
```
I'm not really looking forward to being your build bot.

**Comment by AudriusButkevicius** [comment]
I am looking at jenkins building it, so leave it with me ;)

**Comment by Nutomic** [comment]
Alright cool. Jenkins is more or less broken though.

**Comment by AudriusButkevicius** [comment]
Can you try building it now?
The patch seems to apply fine locally, so I am not sure if the submodule business is working correctly.

**Comment by Nutomic** [comment]
Still not working:
```
Installed Go for linux/amd64 in /home/felix/workspace/syncthing-android/ext/golang/go1.4
Installed commands in /home/felix/workspace/syncthing-android/ext/golang/go1.4/bin
~/workspace/syncthing-android
~/workspace/syncthing-android/ext/golang/go/src ~/workspace/syncthing-android
HEAD is now at 0d81858 go1.7
Applying /home/felix/workspace/syncthing-android/patches/golang/all/dns.patch
patching file net/dnsconfig_unix.go
Hunk #1 FAILED at 9.
Hunk #2 FAILED at 40.
Hunk #3 FAILED at 49.
Hunk #4 FAILED at 126.
4 out of 4 hunks FAILED -- saving rejects to file net/dnsconfig_unix.go.rej
```

**Comment by AudriusButkevicius** [comment]
can you check the content of net/dnsconfig_unix.go?

**Comment by AudriusButkevicius** [comment]
nvm seems some sort of editor issue

**Comment by Nutomic** [comment]
It still shows only 1/8 discovery servers on a fresh install. Do you need any particular logs?

**Comment by AudriusButkevicius** [comment]
It shouldn't be anything todo with this tho.

**Comment by Nutomic** [comment]
It must be because the DNS is not working. The latest release version is showing 5/8 on the same device.

**Comment by AudriusButkevicius** [comment]
In syncthing logs it should print "Using DNS servers", what does it say?

**Comment by AudriusButkevicius** [comment]
Also try setting GODEBUG=netdns=2 and see what it prints.

You can also try setting:

GODEBUG=netdns=go+2
GODEBUG=netdns=cgo+2

and see if that suddenly makes it work, perhaps one of them will work even without the patch.

**Comment by Nutomic** [comment]
`Using DNS servers: [192.168.178.1]`

It's also printing this now all the time (for different ports):
`http: TLS handshake error from 127.0.0.1:41589: remote error: tls: unknown certificate`

With netdns=2 I get this:
```

08-24 23:07:39.934  9029  9071 W SyncthingNativeCode: go package net: built with netgo build tag; using Go's DNS resolver
08-24 23:07:39.934  9029  9071 W SyncthingNativeCode: go package net: hostLookupOrder(discovery-v4-2.syncthing.net) = dns,files
08-24 23:07:39.934  9029  9071 W SyncthingNativeCode: go package net: hostLookupOrder(relays.syncthing.net) = dns,files
08-24 23:07:39.934  9029  9071 W SyncthingNativeCode: go package net: hostLookupOrder(discovery-v4-1.syncthing.net) = dns,files
08-24 23:07:39.934  9029  9071 W SyncthingNativeCode: go package net: hostLookupOrder(discovery-v4-3.syncthing.net) = dns,files
08-24 23:07:39.934  9029  9071 W SyncthingNativeCode: go package net: hostLookupOrder(discovery-v6-1.syncthing.net) = dns,files
08-24 23:07:39.934  9029  9071 W SyncthingNativeCode: go package net: hostLookupOrder(discovery-v6-2.syncthing.net) = dns,files
08-24 23:07:39.935  9029  9071 W SyncthingNativeCode: go package net: hostLookupOrder(discovery-v6-3.syncthing.net) = dns,files
```

The other env vars didn't fix the discovery, and I didn't see anything different in the logs either. It's will probably be easier if you test this stuff yourself.

**Comment by AudriusButkevicius** [comment]
Sadly I nuked my build environment, so just getting that set up is a few hours work.

**Comment by Nutomic** [comment]
If you install Android Studio, it should install the SDK and NDK automatically. So you don't really have to set anything up.

**Comment by Nutomic** [comment]
I'm gonna close this, but feel free to reopen ;)

**Comment by AudriusButkevicius** [comment]
Yeah, need to get back to this.

**Comment by Nutomic** [comment]
Would be cool if we could get a build with the gomobile tools working, so we can hopefully avoid all these hacks.

**Pull request closed without merging**
