### PR TITLE
Add Internal Activity for QR Code Scanner

### LINKED ISSUE #1533: Switch to a less invasive QR scanner app
The Syncthing app requires "Barcode Scanner" by ZXing Team when scanning host IDs.
This app has started requiring more and more permissions that are invasive to users' privacy.
As demonstrated by the screenshot below, it is requesting/using permissions that aren't required to function with Syncthing and that are invasive to privacy; including:
* Device & app history
* Contacts
* Wi-fi

Screenshot

### PR DESCRIPTION
**Pull request by sumit-anantwar**
Resolves #1533 

Add Internal Activity for QR Code Scanner.
Please check the below screen recording for the demo.
https://www.dropbox.com/s/h507363wsmj338q/Screen_Recording_20201006-221716_Syncthing.mp4?dl=0

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
@Catfriend1 what do you think?

**Comment by Catfriend1** [comment]
Cool work:-)! Will try it out during my next dev session and report back. Generally a good idea to remove being dependent from another app. I'm currently using Binary Eye QR Scanner only for Syncthing's purpose.

**Comment by tomasz1986** [comment]
Does the scanner work in the older versions of Android too? Syncthing itself, as of now, supports Android 4.1 and up.

**Comment by sumit-anantwar** [comment]
> @sumit-anantwar Do we really need to bump gradle to use this?

No, we don't need to bump Gradle, I did it out of habit.
If that's an issue, I can roll it back.

**Comment by sumit-anantwar** [comment]
> Does the scanner work in the older versions of Android too? Syncthing itself, as of now, supports Android 4.1 and up.

I am using Zxing itself, just an embedded version of it, published by the team at JourneyApp.
https://github.com/journeyapps/zxing-android-embedded

We are already using this library in a few of our apps. It works reliably.
By default, it supports Android API 24+. If we require support for <24, we just need to add dependency to `zxing-core:3.3.0`.
Will push that commit by EOD today.

**Comment by Catfriend1** [comment]
Looks good to me now. I'm just wondering how to judge implementations/dependency correct from the point of a reviewer. Does anyone else have knowledge about this? E.g. we already have eu.chainfire and this means to me "someone in the past decided to trust it/them". Can we also accept "com.journeyapps:"? I'm a little bit unsure because I saw the discussions about the new Mozilla Firefox F-Droid release a few weeks ago and there, the F-Droid team said "some repositories of implementations are okay, others not" and it was brought up because Mozilla recently had added a new implementation in question.

**Review by AudriusButkevicius — APPROVED** [review]

**Comment by tomasz1986** [comment]
> I'm just wondering how to judge implementations/dependency correct from the point of a reviewer. Does anyone else have knowledge about this?

This is only what I have read here and there, so the information may not be precise, but F-Droid seems to have some kind of a blacklist of disallowed components/dependencies. If they are detected, then the application is automatically rejected from the repository. They keep updating the blacklist, so even if a particular application is OK right now, the situation may change in the future. The criteria seem to be obvious, i.e. any non-free and non-open source additions are rejected.

**Comment by Catfriend1** [comment]
@tomasz1986  :-).

Then I'm all good with it now. Thanks for the contribution @sumit-anantwar  🚀  🎉

**Pull request merged**
