### PR TITLE
Make current proxy text clearer

### PR DESCRIPTION
**Pull request by licaon-kter**
The current one sounds strange `Do not connect through proxy Example <proxy>`, so I setup a proxy to NOT connect? (Yes it got changed when edited...)

### CODE REVIEW

**Comment by Catfriend1** [comment]
I agree with the optimization suggested. Strings would have to be retranslated.

**Comment by AudriusButkevicius** [comment]
I guess this needs to remove all existing strings from all files?

**Comment by Catfriend1** [comment]
@AudriusButkevicius It is okay just changing "app/src/main/res/values/strings.xml". It will need a tx push, people retranslate the string (transifex will make a suggestion based on the old string's meaning and mark it as untranslated) and then tx pull.

**Comment by AudriusButkevicius** [comment]
We'll do a tx push before the release.

**Comment by Catfriend1** [comment]
Can we do one now or let's say about a week for the next release so people have the ability to translate the new UI stuff in the meantime? Last time only english language was available as tx push and the release had only minutes in-between.

**Comment by AudriusButkevicius** [comment]
Whats the big deal with rushing the translations in? It can wait.

**Comment by Catfriend1** [comment]
People would have a translated app on release date. Especially ones that have difficulties with understanding it in english. For me its fine, personally.

**Comment by AudriusButkevicius** [comment]
Right, lets stop talking about this then.

**Pull request merged**
