### PR TITLE
Various visual fixes and resource refactoring

### PR DESCRIPTION
**Pull request by veniosg**
Hi guys. I know this pull request can seem disjointed, I changed things as I found them. What's contained:

* Fixes for 2 issues.
* Updated list item layouts to follow material design guidelines.
* Standardised layout file names.
* Style and theme separation and name standardisation.
* Hiding of empty TextViews in folder list.

Please let me know if there's something I should amend, I'd rather revert than get nothing merged :)

Cheers.

### CODE REVIEW

**Comment by Zillode** [comment]
Thanks for the PR, looks good to me.
We need to wait a bit for @Nutomic, he's on holidays. I'll only merge urgent fixes:)

**Comment by veniosg** [comment]
That's cool, thanks for checking it out so fast!
Let's wait for @Nutomic :)

**Comment by Nutomic** [comment]
You should also add `fixes #xx` at the end of your so the issues get closed.

Other than that, it looks really good to me :+1:

**Comment by veniosg** [comment]
I've added the fixes tags at the end of the commit  messages, just not on on the titles. Pretty sure it'll still work, they'll be closed when the request gets accepted.

**Comment by Nutomic** [comment]
Ah sorry, I missed that. Thank you :)

**Comment by veniosg** [comment]
Thanks for accepting this :)

**Pull request merged**
