### PR TITLE
i18n: Use proper Unicode ellipsis, other clean-ups

### PR DESCRIPTION
**Pull request by acolomb**
Update all `strings.xml` translation files to replace triple full-stop with proper Unicode ellipsis.  Fix other syntax problems and cosmetics in translation source `strings.xml`.

### CODE REVIEW

**Review by imsodin — APPROVED** [review]

**Comment by acolomb** [comment]
Would be good to get this into the rc as well.

**Review by imsodin — DISMISSED** [review]

**Comment by acolomb** [comment]
Oh my... I guess we screwed up on this.  Translation cleanup here, ongoing changes in Weblate, merging of the Weblate PR.  That all happened in suboptimal order, now leading to conflicts everywhere.

Let me try to sort this out.

**Comment by imsodin** [comment]
Crap, sorry - I thought it was all ready to "just use" and wanted to get the translations into the release. Clearly I was too eager, I hope the mess isn't too bad.

**Comment by acolomb** [comment]
Not your fault I guess.  Weblate just made a new attempt #2007, which contained no actual changes.  But it failed to rebase its internal branch onto main even after merging that new PR.  I did a reset there now, after verifying that there were no actual outstanding changes.  Let's see how it behaves next time...

I'm really not sure what parameters would work best for avoiding these conflicts.  Merging PR more often?  Shorter commit interval to make sure it doesn't miss latest changes?  But it does commit changes, rebases and pushes to the PR at the latest when detecting new upstream commits.

Do we have the Webhook enabled here?  See https://docs.weblate.org/en/latest/admin/continuous.html#automatically-receiving-changes-from-github

**Comment by acolomb** [comment]
Anyway, this clean-up is a special occasion.  As long as only regular translation updates trickle in through Weblate, I expect less conflict situations.  Just need one more approval now on this PR because I had to fix the conflicts.  Best done before the next Weblate PR pops up.

**Review by imsodin — APPROVED** [review]
approved but I'll leave the merge to you, I don't grok the ordering constraints.

If you need me to approve and merge in a next iteration (hopefully that won't be necessary), please say so and I'll gladly do that of course.

**Comment by acolomb** [comment]
Ok, I was a bit late, 18 minutes after the next change had trickled in on Weblate.  But it worked without conflicts and we now have a new translation PR #2010 ready for you to merge at will.

**Pull request merged**
