### PR TITLE
Update README.md with buld instructions (question #776)

### PR DESCRIPTION
**Pull request by begetan**
This is Pull Request according the issue [#776](https://github.com/syncthing/syncthing-android/issues/776)

### CODE REVIEW

**Comment by Nutomic** [comment]
Can you please reference the issue in your commit message? Like here: https://github.com/syncthing/syncthing-android/commit/1420ccc1be7c451670c00e799f13262e11ed1303

**Comment by begetan** [comment]
I've added reference number to head and body, but I am not sure how to make URL link in head.

**Comment by Nutomic** [comment]
Ah, you just add "(fixes #776)" to the end of the commit message. Github will link it automatically ;)

**Comment by begetan** [comment]
Ok, I'v just changed commit message. Was not so easy firts time :)

**Comment by Nutomic** [comment]
No problem. Thanks for fixing it :)

**Pull request merged**
