### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Syncthing/Android app strings](https://hosted.weblate.org/projects/syncthing/android/stringsxml/).

It also includes following components:

* [Syncthing/Google Play listings](https://hosted.weblate.org/projects/syncthing/android/play-listings/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by acolomb** [comment]
@imsodin any specific reason why you didn't pull this into the v1.26.1 release?  It should have worked fine.

**Comment by imsodin** [comment]
> @imsodin any specific reason why you didn't pull this into the v1.26.1 release? It should have worked fine. Maybe put that on your release check-list?

That was a hot-fix release and we were only missing a few days of new changes at most. I was actually considering the other way around: Backing out the translation changes already merged given it's a hotfix directly to stable, but considered the risk of messing up weblate as bigger than the chance of anyone finding a problem with translations during the RC phase.

However more broadly I think I would prefer if we could go to the model where weblate uses a separate branch, and then we have a script/task to pull that into main before the first RC - it is quite noisy.

**Comment by acolomb** [comment]
> However more broadly I think I would prefer if we could go to the model where weblate uses a separate branch, and then we have a script/task to pull that into main before the first RC - it is quite noisy.

There are several options available.  We could in fact let Weblate push to a separate branch on our repo, then merge in the changes as desired.  Either through making a PR manually, or merging locally and pushing to main.  Or even using a script to just copy the current state to main and commit that (as long as the release manager has direct commit permission).  In the latter case, we wouldn't even need a separate branch, but can pull directly from Weblate's internal repository.

The basic question is: Do we want to work with Git commits, rebasing, squashing and so on?  Or rather just download the current resulting files and commit them upstream, letting Weblate handle the rebasing internally?

Syncthing main does the latter, but there are occasional conflicts arising because Weblate's Git can sometimes not be cleanly rebased.  Thus we set it to merge instead and live with the occasional alert about the two repos diverging in history.  Weblate is built around Git and we use it as well, so I'd personally prefer a solution that is more aligned with their vision, where an upstream repo and Weblate's internal repo interact through merging commits.  Ideally that is done using merge commits, if we can live with a slightly nonlinear history (actually preserving who contributed which translation).  Rebasing / squashing always has more conflict potential than merging in Git.

**Comment by imsodin** [comment]
@acolomb While I prefer linear history, if merging the weblate branch into main is better/less chance of complication then we can do that. However could you then please configure it to just push to a branch instead of this PR - don't see much value in that, we'll just merge it in as part of releases.

**Comment by acolomb** [comment]
@imsodin Alright, I made the necessary adjustments on Weblate.  Now what you need to do is adding the @weblate to the organization and give it push access to the https://github.com/syncthing/syncthing-android/tree/weblate branch I created for this purpose.  My access permissions are not sufficient to make that change.

**Comment by imsodin** [comment]
Should be working now.

**Comment by acolomb** [comment]
Great.  Just need a translation change now for testing...

@imsodin Note that with the changed workflow, it will be best if you commit something, e.g. the version number bump, during the release process, *right before* pulling in the weblate branch.  That will cause any outstanding changes on Weblate to be committed, even if the commit delay (now reduced to 24 hours again) is not over yet.  Otherwise you might miss out on the last 24 hours of translation work before the release.

**Comment by acolomb** [comment]
Alright, pushing changes to the https://github.com/syncthing/syncthing-android/tree/weblate branch worked.  Now we just need to figure out when to merge those, without blocking feature PRs to get merged to main.

**Comment by imsodin** [comment]
I feel like I am missing something. I thought we'd just merge the weblate branch right before creating an rc release:
1. Bump syncthing
2. Merge translations
3. Bump app version

Is there something else to consider?

**Comment by acolomb** [comment]
That's alright. Just the point "merge translations" means it will merge the *base* of the `weblate` branch as well. The base is the `main` branch, and being kept up to date with each commit. Thus when you merge `weblate` into a separate `release` branch, you're also pulling in anything on `main` that was previously *not* part of `release`.

Thus, branching for a release candidate and pulling in the latest translations again right before the final release will not work as intended. You either have to hold out merging PRs that should not be part of the upcoming release, or stop merging the `weblate` branch between rc and final.

The other solution is to cherry-pick only the translation commits onto `release`, before finalizing it and merging back into `main`.

**Comment by imsodin** [comment]
Thanks for the clarification, got it now.

**Pull request merged**
