### PR TITLE
Syncthing version

### PR DESCRIPTION
**Pull request by lkwg82**
This adds the current syncthing version to the slider. No more open the web gui to check the version.

screenshot1

### CODE REVIEW

**Comment by capi** [comment]
First this gets a :+1: from me.

Second, I'd squash the two commits into one.

**Comment by lkwg82** [comment]
@capi thx and what was this github feature to squash commits?

**Comment by capi** [comment]
@lkwg82 It's a git feature. Use `git rebase -i` and mark them all as "fixup". Then make a force-push to this branch and it will update the Pull Request.

**Comment by lkwg82** [comment]
@capi I meant the github ui feature to squash commits in UI, anyway I did it

**Comment by lkwg82** [comment]
So any hints or may I merge this?

**Comment by AudriusButkevicius** [comment]
Wait for @Nutomic

**Comment by Nutomic** [comment]
Using a JSON library is definitely a good idea, seeing how much boilerplate code we have there.

I'm not sure if it's a good idea to put the version into the drawer. On larger devices that's fine, but on smaller devices it means that the share and restart buttons can be pushed out (so you have to scroll to them). Any opinions on that?

Other than that, it looks good to me.

**Comment by lkwg82** [comment]
mhm, I just checked the web gui, what are the most important informations. But you are right. I dont know.

**Comment by Nutomic** [comment]
Alternatively, we could change the scrollview so that it only contains the info view on top, and not the buttons. That way, people with a smaller screen wouldn't miss so much.

**Comment by lkwg82** [comment]
What do you mean?

**Comment by Nutomic** [comment]
You can test this by rotating your device into landscape: When opening the drawer, and it doesn't all fit on the screen, you can scroll the info on top, together with the web gui/share/restart buttons. We could change it so that only the info view scroll, and the buttons are static.

**Pull request merged**
