### PR TITLE
Fix contrast of top app bar

### LINKED ISSUE #1915: Latest update makes headers nearly unreadable when using dark mode
Please see the top of this screenshot:
Screenshot_20230613-012529297

Previously, the header text was not white-on-light. (EDITED.)

### Version Information

    App Version: 1.23.5
    Syncthing Version: 1.23.5
    Android Version: Android 13

### PR DESCRIPTION
**Pull request by Bnyro**
closes #1915

### CODE REVIEW

**Comment by imsodin** [comment]
Thanks a lot for the super speedy reaction!  
Would you mind posting a screenshot?

**Comment by Bnyro** [comment]
Unfortunately, I currently don't have a development setup for syncthing, so the app crashes because the go code is not included. However, I can make screenshots from the startup. 
I just noticed there are issues in light mode now, I'll force push the branch in a sec and send screenshots then.

**Comment by Bnyro** [comment]
Screenshot_20230613-104734_Syncthing
Screenshot_20230613-104742_Syncthing

**Comment by Bnyro** [comment]
I had to make some other adjustments now to fix the icon colors in the top bar and prevent different elevations of the toolbar and the tab layout.

**Comment by Bnyro** [comment]
Yes, we don't apply any custom style to dialogs, we use the stock ones from Material Design 3. The same behavior is visible in other apps using Material Design 3.
(That's why I always use the dark mode, it just looks way better :p)

**Review by imsodin — APPROVED** [review]

**Comment by LinuxOnTheDesktop** [comment]
It seems to me - if I may say so - that in both screenshots above there should be a little more contrast.

Also - if this is a separate point - in the second screenshot, the background to the rounded box, and/or the text within that box, are a little too yellow (as if some sort of eyecare filter has been applied; such filters should be left to the OS or to the user).

Still, the dark mode is now _legible_, which is the main thing!

**Comment by imsodin** [comment]
As far as I understand we now don't apply any custom theming, but use some material dark google pre-defined stuff. Which I like on one hand, as it's less stuff to maintain and get wrong, and dislike on the other hand, for (some of) the reasons you outline. However the maintenance part wins big time - so yeah, maybe you can convince google to stop that low-contrast, flatness craze (or it will blow over eventually) :)

**Comment by LinuxOnTheDesktop** [comment]
@imsodin: thanks. It's no problem. I'll just have a word with Ms Google - via her search bar - and ask her to improve things. Give it a day or two. :)

**Pull request merged**
