### PR TITLE
build: add gradle.properties to select java version 8

### PR DESCRIPTION
**Pull request by imsodin**
Apparently the current default java version on my system is 10, and the resulting error from gradle is totally clear:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

In order to spare other new (and not java-versed) contributors this headache, lets just specify this version.

### CODE REVIEW

**Comment by AudriusButkevicius** [comment]
And what if I am on Windows or my java is in a different location?

**Comment by imsodin** [comment]
... and there really seems to be no way (except parsing `java -version` or some similar BS) to give a meaningful error - every journey into java/android land is such a dream. I'll settle for a readme note then.

**Comment by Nutomic** [comment]
Looks like we just have to update gradle. Will do this later.

https://www.infoq.com/news/2018/05/gradle-releases-version-4.7

**Comment by Nutomic** [comment]
I guess Java 10 is not supported by the Android build tools, I was still getting errors after upgrading everything.

**Pull request merged**
