### PR TITLE
build x86_64 binary to accomodate google play

### PR DESCRIPTION
**Pull request by imsodin**
As @Catfriend1 [pointed out a while ago ](https://forum.syncthing.net/t/new-release-is-tagged-and-built-for-tomorrow/13114/15) (thanks!) and the play console is nagging whenever I do a release, we also need to provide the 64bit variant of x86 build. I just copied the section Catfriend1 pointed me to: https://github.com/Catfriend1/syncthing-android/blob/5778faeaf9941f06f435d4ffebae19d1051f0a46/syncthing/build-syncthing.py#L47

### CODE REVIEW

**Comment by Catfriend1** [comment]
Looks good to me, lets wait for the CI to succeed.

**Comment by Catfriend1** [comment]
> [19:51:13][Step 1/1] 16 is less than minimum platform for x86_64 (21)

**Comment by Catfriend1** [comment]
> 19:56:29][Step 1/1] Building syncthing
[19:56:29][Step 1/1] Traceback (most recent call last):
[19:56:29][Step 1/1]   File "./build-syncthing.py", line 125, in <module>
[19:56:29][Step 1/1]     ] + pkg_argument + ['-no-upgrade', 'build'], env=environ, cwd=syncthing_dir)
[19:56:29][Step 1/1] KeyError: 'cc'

**Comment by Catfriend1** [comment]
Yes just wanted to say that my build script no longer has minsdk and directly assigns clang env var... You're really fast & furious ;-)

**Comment by imsodin** [comment]
I don't get the travis problem - it says it builds the new ndk but then fails when actually trying to use gcc from that ndk:

```
Building standalone NDK for x86_64 API level 21 to /home/travis/build/syncthing/syncthing-android/syncthing/gobuild/standalone-ndk/android-21-amd64
[...]
runtime/cgo
# runtime/cgo
fork/exec /home/travis/build/syncthing/syncthing-android/syncthing/gobuild/standalone-ndk/android-21-amd64/bin/x86_64-linux-android21-clang: no such file or directory
```

If anyone knows a fix that'd be nice, otherwise I'll just disable travis (what's it there for anyway?).

**Comment by imsodin** [comment]
Thanks Audrius, that was the issue. I'll close this PR and reopen and merge after 1.3.1 final is released, as merging requires deploying a new build image, which would also apply to that release.

**Comment by imsodin** [comment]
Now that the release is done, lets see whether this still flies and ship it.

**Pull request merged**
