### PR TITLE
Bump 0.12.1

### PR DESCRIPTION
**Pull request by Zillode**

### CODE REVIEW

**Comment by dper** [comment]
Would this let the Android client work with other 0.12 clients? Because that would be just amazing.

**Comment by licaon-kter** [comment]
@dper 0.7.0-betas work ok, already.

**Comment by chucic** [comment]
@licaon-kter Not for me: #473

**Comment by licaon-kter** [comment]
Oh, ok, I only saw https://github.com/syncthing/syncthing-gtk/issues/216 on my setup, but I only have 1 host.

**Comment by chucic** [comment]
Yes, I think it's same root cause. Apart from that it's working fine ;-)

**Comment by Nutomic** [comment]
Looks good!

Can you reference #470 in the commit message before merging?

**Pull request merged**
