### PR TITLE
fix parseInt exception - fixes https://github.com/syncthing/syncthing…

### PR DESCRIPTION
**Pull request by ghost**
Purpose
If the user enters an invalid integer in syncthing options for allowed bandwidth, a message is shown telling the accepted value range.

Testing
Verified working on Android 7.1.2 @ lg-h815.

### CODE REVIEW

**Review by AudriusButkevicius — APPROVED** [review]

**Comment by AudriusButkevicius** [comment]
Isn't min value negative?

**Comment by Catfriend1** [comment]
@AudriusButkevicius Right, fixed it as negative values don't make sense here.

**Comment by AudriusButkevicius** [comment]
Isn't there an unsigined integer in java? People can still put in -1... Also, isn't there a way to validate this in the view/layout?

**Comment by Catfriend1** [comment]
Hmm yes -1 may be a point but I would just suggest drop this case unhandled as syncthing core ui also does allow setting -1. People need to understand the options. Else we could make an if to check if its negative... Really necessary?

**Comment by Catfriend1** [comment]
@AudriusButkevicius I looked again at the implementation and found it is correct. Java has no unsigned integers plus the layout disallows entering negative values. So, lgtm please.

**Comment by AudriusButkevicius** [comment]
https://developer.android.com/reference/android/widget/TextView.html#attr_android:numeric

It seems that you van force only positive numbers in the view.

**Pull request merged**
